CREATE OR ALTER TRIGGER FATURAMENTO_UPDATE ON [ITENS NOTAS FISCAIS] AFTER INSERT
AS BEGIN
    DECLARE @DATA DATE = CAST (GETDATE()AS DATE)
    DECLARE @FATURAMENTO MONEY
    DECLARE @DATA_ATUAL DATE
    SELECT @FATURAMENTO = SUM(PREÇO*QUANTIDADE) FROM [ITENS NOTAS FISCAIS]
    SELECT @DATA_ATUAL = DATA_NF FROM FATURAMENTO
    
    IF @DATA = @DATA_ATUAL
        UPDATE FATURAMENTO SET DATA_NF = @DATA, FAT = @FATURAMENTO
    ELSE
        INSERT FATURAMENTO VALUES(@DATA, @FATURAMENTO)
END


INSERT [ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PREÇO) VALUES
    (110,1004327, 20, 140.99)

CREATE TABLE FATURAMENTO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DATA_NF DATE,
    FAT MONEY
)

SELECT *FROM FATURAMENTO