CREATE DATABASE MERCADINHO
USE MERCADINHO

CREATE TABLE CLIENTE(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NOME VARCHAR(30),
	CPF VARCHAR(12),
	DATACAD DATE NOT NULL DEFAULT GETDATE()
)

CREATE TABLE PRODUTO(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NOME VARCHAR(30),
	PRECO MONEY
)

CREATE TABLE VENDA(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	ID_CLIENTE INT,
	ID_PRODUTO INT,
	DATA_VENDA DATE NOT NULL DEFAULT GETDATE()
)

ALTER TABLE VENDA
	ADD QUANTIDADE INT 

SELECT CLIENTE.NOME, PRODUTO.NOME AS PRODUTO, PRODUTO.PRECO, VENDA.QUANTIDADE, VENDA.QUANTIDADE*PRODUTO.PRECO as PreçoFinal FROM VENDA 
JOIN CLIENTE ON CLIENTE.ID = VENDA.ID_CLIENTE
JOIN PRODUTO ON PRODUTO.ID = VENDA.ID_PRODUTO


INSERT VENDA (ID_CLIENTE, ID_PRODUTO, QUANTIDADE)
VALUES
	(1,1,3),
	(2,2,4),
	(1,2,3),
	(2,3,4);

SELECT * FROM VENDA

DELETE FROM VENDA WHERE QUANTIDADE IS NULL


lalllala me mama aqui
