CREATE DATABASE MERCADO

USE MERCADO

CREATE TABLE CLIENTE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(12) NOT NULL,
	DATA_CAD DATE NOT NULL DEFAULT GETDATE()
)


CREATE TABLE PRODUTO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	PRECO MONEY
)

CREATE TABLE VENDA(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_PROD INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	DATA_VENDA DATE NOT NULL DEFAULT GETDATE()
)


INSERT VENDA(ID_PROD, ID_CLIENTE) VALUES (4,4)

SELECT P.NOME, C.NOME, P.PRECO, DATA_VENDA FROM VENDA
JOIN PRODUTO P ON P.ID = ID_PROD
JOIN CLIENTE C ON C.ID = ID_CLIENTE
