CREATE DATABASE ESTACIONAMENTO_JOQUINHA

USE ESTACIONAMENTO_JOQUINHA

CREATE TABLE CLIENTE(

    CPF VARCHAR(12) PRIMARY KEY,
    NOME VARCHAR(30),
    DT_NASC DATE
)

CREATE TABLE MODELO(
    ID INT IDENTITY (1,1) PRIMARY KEY,
    NOME VARCHAR(40)
)

CREATE TABLE PATIO(
    ID INT IDENTITY (1,1) PRIMARY KEY,
    ENDERECO VARCHAR(40),
    CAPACIDADE INT
)

CREATE TABLE VEICULO(
    
)