
SELECT A.NOME, COUNT(B.CPF) AS QT 
FROM [TABELA DE CLIENTES] A LEFT JOIN [NOTAS FISCAIS] B ON A.CPF = B.CPF 
GROUP BY A.NOME

SELECT A.NOME
FROM [TABELA DE CLIENTES] A LEFT JOIN [NOTAS FISCAIS] B ON A.CPF = B.CPF
WHERE B.CPF IS NULL

SELECT C.BAIRRO, C.NOME FROM [TABELA DE CLIENTES] C 
UNION ALL
SELECT V.BAIRRO, V.NOME FROM [TABELA DE VENDEDORES] V

SELECT C.BAIRRO, C.NOME AS CLIENTES, V.NOME AS VENDEDORES FROM [TABELA DE CLIENTES] C
JOIN [TABELA DE VENDEDORES] V
ON V.BAIRRO = C.BAIRRO


SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT BAIRRO FROM [TABELA DE VENDEDORES])


SELECT NOVA_CONSULTA.EMBALAGEM, NOVA_CONSULTA.MAX_PRECO 
FROM( SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO FROM TABELADEPRODUTOS GROUP BY EMBALAGEM) NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PRECO <=5



HAVING COUNT(B.CPF) = 0

SELECT * FROM [NOTAS FISCAIS]

SELECT * FROM [TABELA DE CLIENTES]

SELECT A.NOME, COUNT(*) AS NOME
FROM[TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B ON A.CPF = B.CPF

SELECT CPF, COUNT(*) AS NOME FROM [NOTAS FISCAIS] GROUP BY CPF 


SELECT CPF WHERE 













CREATE DATABASE AULA04

USE AULA04

CREATE TABLE EDITORA(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(40)
)

CREATE TABLE LIVROS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(40),
	ID_EDITORA INT FOREIGN KEY REFERENCES EDITORA(ID)
)

INSERT EDITORA VALUES 
('MANAUS'),
('SARAIVA'),
('PEDROSILVA'),
('CIA DAS LETRAS')

INSERT LIVROS VALUES
('CHAPEUZINHO VERMELHO',4),
('LOBO MAL',1),
('VOVOZINHA',3),
('A CABANA',2),
('BIBLIA',4),
('JOGOS VORAZES',2),
('RECEITAS DA DONA MARIA',4),
('MASTERCHEF EM 1 DIA',4)



SELECT E.NOME, COUNT(L.ID_EDITORA) 
FROM EDITORA E 
JOIN LIVROS L ON
L.ID_EDITORA = E.ID
GROUP BY (E.NOME)

SELECT NOME FROM LIVROS WHERE LIVROS.ID_EDITORA IN (SELECT ID FROM EDITORA WHERE NOME = 'CIA DAS LETRAS')






CREATE TABLE PRODUTOS_CAROS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(90),
	PRECO MONEY
)
INSERT INTO PRODUTOS_CAROS(NOME,PRECO)(
	SELECT P.[NOME DO PRODUTO], P.[PREÇO DE LISTA] FROM TABELADEPRODUTOS P
	WHERE [PREÇO DE LISTA] >= 15
)








