CREATE DATABASE BIBLIOTECA

USE BIBLIOTECA

CREATE TABLE USUARIO(
    CPF VARCHAR(12) PRIMARY KEY,
    NOME VARCHAR(40),
    CONTATO VARCHAR(14)
)

CREATE TABLE LIVRO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(40),
    GENERO VARCHAR(40)
)

CREATE TABLE EXEMPLAR(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_LIVRO INT FOREIGN KEY REFERENCES LIVRO(ID),
    DISPONIVEL BIT
)

CREATE TABLE BIBLIOTECARIA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CPF VARCHAR(12),
    NOME VARCHAR(40),
    TURNO INT
)

CREATE TABLE EMPRESTIMO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DATE_OUT DATE  DEFAULT GETDATE(),
    ID_EXEMPLAR INT FOREIGN KEY REFERENCES EXEMPLAR(ID),
    ID_BIBLIOTECARIA INT FOREIGN KEY REFERENCES BIBLIOTECARIA(ID),
    ID_USER VARCHAR(12) FOREIGN KEY REFERENCES USUARIO(CPF)
)
